---
swagger: 2.0
info:
  description: This is a demo
  version: 1.0.0
  title: DATA WARE HOUSE
  contact:
    email: dataware@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: virtserver.swaggerhub.com
basePath: /delilah/1.0.0
tags:
- name: admin
  description: Secured Admin-only calls
- name: client
  description: Operations available to regular developers
schemes:
- https
paths:
  /proyectos:
    get:
      summary: lista los proyectos que están siendo evaluados
      parameters:
        - in: path
          type: integer
          name: id
          description: order Id
          required: true
    post:
      summary: confirma la carga de un nuevo proyecto
  /proyectos/{id}:
    put: 
      summary: actualiza el estado de un proyecto
    get:
      summary: muestra información de un proyecto
      parameters:
        - in: path
          type: integer
          name: id
          description: order Id
          required: true
    delete:
      summary: borra un proyecto de la la base de datos 
  /evaluadores:
    get:
      summary: lista los y las evaluadores/as
    post:
      summary: agrega un nuevo evaluador/a disponble para revisar proyectos
  /evaluadores/{id}:
    delete:
      summary: quita un  evaluador/a de la base de datos
    put:
      summary: actualiza la información del/ de la evualuador/a 
      parameters:
        - in: path
          type: integer
          name: id
          description: product Id
          required: true
  /contactos:
    get:
      summary: lista los contactos
      produces:
      - application/json
    post:
      summary: agrega un nuevo contacto
      parameters:
        - in: body
          name: body
          description: Update an user
          required: true
      responses:
        '200':
          description: successful operation
        '404':
          description: Not Found
        '500':
          description: Internal server error
  /contactos/{id}:
    get:
      summary: expone los datos de un contacto
    put:
      summary: actualiza los datos de un contacto
      parameters:
          - in: path
            type: integer
            name: id
            description: contact Id
            required: true
          - in: body
            name: body
            description: Update an contact
            required: true
      responses:
        '200':
          description: successful operation
        '404':
          description: Not Found
        '500':
          description: Internal server error
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'